### ISSUE TITLE
Installation on Windows 10 using pip fails, and VERY outdated pip 7.2.0 keeps getting installed, requiring me to upgrade pip again

### ISSUE THREAD

**Issue by aarek-eng** [kdeldycke/meta-package-manager#300] opened 2021-06-09 14:52 UTC
I don't know what I'm doing wrong. [The PyPl page for this package says it supports Windows](https://pypi.org/project/meta-package-manager/), and I'm following the instructions to the letter when it comes to installing [Python](https://packaging.python.org/tutorials/installing-packages/#ensure-you-can-run-python-from-the-command-line), [Pip](https://pip.pypa.io/en/stable/installing/), and this package. This is the result, with PowerShell7, in Admin mode. The prompt goes RED from "Exception" till  "Unable to locate finder for 'pip._vendor.distlib'"

```
PS C:\Windows\system32> py -m pip install meta-package-manager
Collecting meta-package-manager
  Downloading https://files.pythonhosted.org/packages/62/97/03714f808671ba802acebaf69ed3ea0334d8dcbf764dd6e0ce3b3b6022c5/meta_package_manager-4.1.0-py3-none-any.whl (97kB)
    100% |████████████████████████████████| 98kB 716kB/s
Collecting cli-helpers<3.0.0,>=2.1.0 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/3d/fb/77b7e149d8d7197cdec71413fe60a7f870d69fa77d659d7cb0ebaa221276/cli_helpers-2.1.0-py3-none-any.whl
Collecting tomlkit<0.8.0,>=0.7.0 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/eb/ef/5bd27c1a8040874cc863c263bf38857b5607017b656943c6c93b29bc8f42/tomlkit-0.7.2-py2.py3-none-any.whl
Collecting click-log<0.4.0,>=0.3.2 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/38/52/a9dbb622f40ceeb09df141d855062cc9fbb38011f0ad8caee0cd840f399c/click_log-0.3.2-py2.py3-none-any.whl
Collecting boltons<21.0.0,>=20.2.1 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/71/e1/e7979a4a6d4b296b5935e926549fff540f7670ddaf09bbf137e2b022c039/boltons-20.2.1-py2.py3-none-any.whl (170kB)
    100% |████████████████████████████████| 172kB 460kB/s
Collecting click-help-colors<0.10,>=0.9 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/3a/dd/9c13d602b62f373cfb343082cdf5565ae87fa7e01e6378984200f7477b5e/click_help_colors-0.9-py3-none-any.whl
Collecting simplejson<4.0.0,>=3.17.2 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/49/45/a16db4f0fa383aaf0676fb7e3c660304fe390415c243f41a77c7f917d59b/simplejson-3.17.2.tar.gz (83kB)
    100% |████████████████████████████████| 86kB 862kB/s
Collecting click<8.0.0,>=7.1.2 (from meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
    100% |████████████████████████████████| 86kB 1.3MB/s
Collecting terminaltables>=3.0.0 (from cli-helpers<3.0.0,>=2.1.0->meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/9b/c4/4a21174f32f8a7e1104798c445dacdc1d4df86f2f26722767034e4de4bff/terminaltables-3.1.0.tar.gz
Collecting configobj>=5.0.5 (from cli-helpers<3.0.0,>=2.1.0->meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz
Collecting tabulate[widechars]>=0.8.2 (from cli-helpers<3.0.0,>=2.1.0->meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/ca/80/7c0cad11bd99985cfe7c09427ee0b4f9bd6b048bd13d4ffb32c6db237dfb/tabulate-0.8.9-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in c:\users\erika\appdata\local\programs\python\python39\lib\site-packages (from configobj>=5.0.5->cli-helpers<3.0.0,>=2.1.0->meta-package-manager)
Collecting wcwidth (from tabulate[widechars]>=0.8.2->cli-helpers<3.0.0,>=2.1.0->meta-package-manager)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Building wheels for collected packages: simplejson, terminaltables, configobj
  Running setup.py bdist_wheel for simplejson
  Stored in directory: C:\Users\ERIKA\AppData\Local\pip\Cache\wheels\6f\f5\40\b670726278e9929d5aba2a3d4d9580209932f93152f3d86e2b
  Running setup.py bdist_wheel for terminaltables
  Stored in directory: C:\Users\ERIKA\AppData\Local\pip\Cache\wheels\30\6b\50\6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
  Running setup.py bdist_wheel for configobj
  Stored in directory: C:\Users\ERIKA\AppData\Local\pip\Cache\wheels\f1\e4\16\4981ca97c2d65106b49861e0b35e2660695be7219a2d351ee0
Successfully built simplejson terminaltables configobj
Installing collected packages: terminaltables, configobj, wcwidth, tabulate, cli-helpers, tomlkit, click, click-log, boltons, click-help-colors, simplejson, meta-package-manager
Exception:
Traceback (most recent call last):
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\commands\install.py", line 308, in run
    requirement_set.install(
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\req\req_set.py", line 642, in install
    requirement.install(
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\req\req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\req\req_install.py", line 992, in move_wheel_files
    move_wheel_files(
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\wheel.py", line 479, in move_wheel_files
    maker.make_multiple(['%s = %s' % kv for kv in console.items()])
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 364, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 353, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 257, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 193, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\scripts.py", line 332, in _get_launcher
    result = finder(distlib_package).find(name).bytes
  File "C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages\pip\_vendor\distlib\resources.py", line 324, in finder
    raise DistlibException('Unable to locate finder for %r' % package)
pip._vendor.distlib.DistlibException: Unable to locate finder for 'pip._vendor.distlib'
You are using pip version 7.1.2, however version 21.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Windows\system32> py -m pip --version
pip 7.1.2 from C:\Users\ERIKA\AppData\Roaming\Python\Python39\site-packages (python 3.9)

```

I would appre

**Comment by kdeldycke** [comment] 2021-06-09 15:08
Looks like you have an outdated version of `pip` itself. I guess you can upgrade it with:

```ps
PS C:\Windows\system32> py -m pip install --upgrade pip
```

**Comment by kdeldycke** [comment] 2021-09-27 20:39
Did you tried to replicate the issue with the latest mpm version?

**Comment by kdeldycke** [comment] 2021-09-30 17:39
I'm closing the issue for now. Feel free to reopen if you can reproduce the issue,

**Closed by kdeldycke** 2021-09-30 17:39 UTC
Labels: 📦 manager: pip, 🖥 platform: Windows, ❓ question
