### ISSUE TITLE
Error when running 2.5.0 installed via pip3

### ISSUE THREAD

**Issue by rkrug** [kdeldycke/meta-package-manager#40] opened 2017-09-04 08:28 UTC
I am using homebrew, and get the following error:

```
10:24 $ mpm
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 7, in <module>
    from meta_package_manager.cli import cli
  File "/usr/local/lib/python3.6/site-packages/meta_package_manager/cli.py", line 80, in <module>
    @click_log.init(logger)
AttributeError: module 'click_log' has no attribute 'init'
```

Let me know if you need any further info.

Rainer

**Comment by pdelre** [comment] 2017-09-07 12:27
Dupe of #39 but a new release has not been cut for the recent commits in August.

@kdeldycke will you be doing a new release soon?

**Comment by kdeldycke** [comment] 2017-09-09 16:34
@pdelre Just trying to make all unittests pass before releasing 2.6.0. Travis jobs gets stuck for peripheral issues though. So I might loose patience and release it anyway, without the unittests passing.

**Closed by kdeldycke** 2017-09-09 16:34 UTC

**Comment by kdeldycke** [comment] 2017-09-10 22:47
mpm 2.6.0 has just been released! :)

**Comment by rkrug** [comment] 2017-09-12 14:30
Thanks - upgraded and working
