### ISSUE TITLE
Fails on apm (all latest versions)

### ISSUE THREAD

**Issue by beorn** [kdeldycke/meta-package-manager#46] opened 2018-08-02 09:53 UTC
```console
% mpm --version                    
mpm, version 2.7.0

% apm --version
apm  1.19.0
npm  3.10.10
node 6.9.5 x64
atom 1.29.0
python 2.7.15
git 2.18.0

% mpm --continue-on-error installed
warning: Skip unavailable apt manager.
Traceback (most recent call last):
  File "/usr/local/bin/mpm", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/cli.py", line 256, in installed
    'packages': list(manager.installed.values())}
  File "/usr/local/lib/python2.7/site-packages/boltons/cacheutils.py", line 660, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/usr/local/lib/python2.7/site-packages/meta_package_manager/managers/apm.py", line 158, in installed
    'installed_version': package['version']}

```

**Comment by kdeldycke** [comment] 2019-01-02 18:55
I'm sorry I can't reproduce the issue:
```$ brew cask install atom
Updating Homebrew...
==> Downloading https://github.com/atom/atom/releases/download/v1.33.1/atom-mac.zip
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/3228505/70459a00-0399-11e9-96ae-
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'atom'.
==> Installing Cask atom
==> Moving App 'Atom.app' to '/Applications/Atom.app'.
==> Linking Binary 'apm' to '/usr/local/bin/apm'.
==> Linking Binary 'atom.sh' to '/usr/local/bin/atom'.
🍺  atom was successfully installed!

$ mpm --version
mpm, version 2.7.0

19:51 $ apm --version
apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.33.1
python 3.7.2
git 2.20.1

$ mpm --continue-on-error installed
warning: Skip unavailable cask manager.
warning: Skip unavailable npm manager.
warning: Skip unavailable apt manager.
warning: Skip unavailable pip2 manager.
╒═════════════════════════════╤═════════════════════════════╤═══════════╤═════════════════════╕
│ Package name                │ ID                          │ Manager   │ Installed version   │
╞═════════════════════════════╪═════════════════════════════╪═══════════╪═════════════════════╡
│ about                       │ about                       │ apm       │ 1.9.1               │
├─────────────────────────────┼─────────────────────────────┼───────────┼─────────────────────┤
(...)
╘═════════════════════════════╧═════════════════════════════╧═══════════╧═════════════════════╛
401 packages found (105 from apm, 165 from brew, 16 from gem, 6 from mas, 109 from pip3).
```

I'm going to close the issue then.

**Closed by kdeldycke** 2019-01-02 18:55 UTC
Labels: bug, manager: apm
